"""Set Parameters for the APP here...."""

import os

file_dir = os.path.dirname(os.path.realpath(__file__))

# BROADCAST KNOWN FACE ENCODINGS OR PEOPLE TO FIND
KNOWN_FACE_TOPIC = "target_faces"

# TOPIC USED TO PUBLISH ALL FRAME OBJECTS
FRAME_TOPIC = "raw_frames"
# TOPIC USED TO PUBLISH ALL FRAME OBJECTS
PROCESSED_FRAME_TOPIC = "processed_frames"

# PREDICTION TOPIC PREFIX, EACH CAMERA GETS NEW TOPIC FOR PUBLISHED PREDICTIONS
PREDICTION_TOPIC_PREFIX = "{}_{}".format("predicted_objects", FRAME_TOPIC)
# ENDPOINT FOR VIDEO STREAMS
C_FRONT_ENDPOINT = "http://d3tj01z94i74qz.cloudfront.net/"
# CAMERA URL INDEXES
# CAMERAS = [1, 5]  # [Michelle, Jeff]
CAMERAS = [3, 4]  # [Wagner, Jensen]

# TOTAL CAMERAS TO BE USED --> USED FOR FULL URL
TOTAL_CAMERAS = len(CAMERAS)


# USE RAW CV2 STREAMING or FAST BUT LESS FRAMES
USE_RAW_CV2_STREAMING = False

# TOPIC PARTITIONS
SET_PARTITIONS = 16

ORIGINAL_PREFIX = "predicted"
PREDICTED_PREFIX = "predicted"
